title = "Understanding the 2016 Election"
canonifyurls = true
baseURL = "https://whathappened.in/"
author = "Ben"
theme = "inkblotty"
paginate = 10

languageCode = "en-us"
DefaultContentLanguage = "en-us"
hasCJKLanguage = "true"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

disqusShortname = "voting-2016"
googleAnalytics = "UA-124735498-2"

summaryLength=150

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[[menu.main]]
  identifier = "posts"
  name = "All Posts"
  url = "https://whathappened.in/2016/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "https://whathappened.in/about/"
  weight = 10

[[menu.main]]
  identifier = "feedback"
  name = "Give Feedback"
  url = "https://whathappened.in/2016/feedback/"
  weight = 10


[Params]
  readmore = true
  css = ["css/custom.css"]

[outputs]                          # c.f. https://gohugo.io/templates/output-formats/
  home = ["HTML", "RSS"]
  page =  ["HTML"]
  section =  ["HTML", "RSS"]
  taxonomyTerm =  ["HTML", "RSS"]
  taxonomy =  ["HTML", "RSS"]

[sitemap]
  filename = "sitemap.xml"  # c.f. https://gohugo.io/templates/sitemap-template/#configure-sitemap-xml

[Author]
    name = "Ben"
